"""Shared issue tracker primitives."""

from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
import re
import tempfile


VALID_ISSUE_STATUSES = {"active", "planned", "investigating", "in_progress", "completed"}
VALID_ISSUE_PRIORITIES = {"high", "medium", "low"}
GENERATED_FILE_MARKER = "generated by `issuekit generate-indexes`"
WORKFLOW_TOKEN_PATTERN = re.compile(r"^[a-z0-9][a-z0-9_-]{0,31}$")
MANAGED_FRONTMATTER_KEYS = {
    "id",
    "status",
    "priority",
    "created",
    "completed",
    "assignee",
    "stage",
    "implementer",
    "author",
    "title",
}
MOJIBAKE_PATTERN = re.compile(
    "\u7e67|\u7e3a|\u8b41|\u8373|\u87b3|\u8708|\u9ae2|\ufffd"
)
NON_ASCII_PATTERN = re.compile(r"[^\x00-\x7F]")


@dataclass(frozen=True)
class Frontmatter:
    data: dict[str, str]
    body: str
    has_frontmatter: bool


@dataclass(frozen=True)
class Issue:
    id: int | None
    file_name_id: int | None
    file_name: str
    file_path: Path
    relative_path: str
    title: str
    status: str
    issue_status: str
    created: str
    completed: str
    priority: str
    assignee: str
    stage: str
    implementer: str
    author: str
    content: str
    frontmatter: Frontmatter
    decode_error: bool = False


def issue_dict(issue: "Issue", *, include_body: bool = False) -> dict[str, object]:
    """Serialize an issue for JSON output.

    Shared by the MCP server and the CLI so both paths emit identical payloads.
    """
    data: dict[str, object] = {
        "id": issue.id,
        "title": issue.title,
        "status": issue.issue_status,
        "assignee": issue.assignee,
        "stage": issue.stage,
        "implementer": issue.implementer,
        "author": issue.author,
        "file": issue.relative_path,
    }
    if include_body:
        data["body"] = issue.frontmatter.body
    return data


def parse_issue_id(file_name: str) -> int | None:
    match = re.match(r"^(\d+)_.*\.md$", file_name)
    return int(match.group(1)) if match else None


def parse_issue_frontmatter(content: str) -> Frontmatter:
    if content.startswith("\ufeff"):
        content = content[1:]

    if not (content.startswith("---\n") or content.startswith("---\r\n")):
        return Frontmatter(data={}, body=content, has_frontmatter=False)

    match = re.match(r"^---\r?\n([\s\S]*?)\r?\n---\r?\n?", content)
    if not match:
        return Frontmatter(data={}, body=content, has_frontmatter=False)

    data: dict[str, str] = {}
    for raw_line in re.split(r"\r?\n", match.group(1)):
        line = raw_line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        if (
            len(value) >= 2
            and ((value[0] == '"' and value[-1] == '"') or (value[0] == "'" and value[-1] == "'"))
        ):
            value = value[1:-1]
        data[key.strip()] = value

    return Frontmatter(data=data, body=content[match.end() :], has_frontmatter=True)


def format_issue_frontmatter(data: dict[str, object]) -> str:
    fixed_keys = MANAGED_FRONTMATTER_KEYS
    fields = [
        ("id", data.get("id")),
        ("status", data.get("status")),
        ("priority", data.get("priority")),
        ("created", data.get("created")),
        ("completed", data.get("completed") or ""),
        ("assignee", data.get("assignee") or ""),
        ("stage", data.get("stage") or ""),
        ("implementer", data.get("implementer") or ""),
        ("author", data.get("author") or ""),
    ]
    fields.extend((key, data.get(key)) for key in data if key not in fixed_keys)
    fields.append(("title", data.get("title")))
    lines = []
    for key, value in fields:
        if key in {"assignee", "stage", "implementer", "author"} and not value:
            continue
        lines.append(f"{key}: {'' if value is None else value}")
    body = "\n".join(lines)
    return f"---\n{body}\n---\n\n"


def passthrough_frontmatter(data: dict[str, str]) -> dict[str, str]:
    return {key: value for key, value in data.items() if key not in MANAGED_FRONTMATTER_KEYS}


def write_issue_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    normalized_content = content.replace("\r\n", "\n").replace("\r", "\n")
    fd, temp_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
    )
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(normalized_content)
        os.replace(temp_path, path)
    finally:
        temp_path.unlink(missing_ok=True)


def parse_frontmatter_id(value: object) -> int | None:
    if value is None or value == "":
        return None
    try:
        return int(str(value))
    except ValueError:
        return None


def get_issue_heading(content: str) -> re.Match[str] | None:
    return re.search(r"^#\s+Issue\s+#\d+:\s*(.+)$", content, re.MULTILINE) or re.search(
        r"^#\s+(.+)$", content, re.MULTILINE
    )


def read_issues(issues_dir: Path | str, directory_status: str) -> list[Issue]:
    issues_path = Path(issues_dir)
    source_dir = issues_path / directory_status
    if not source_dir.exists():
        return []

    issues: list[Issue] = []
    for file_path in source_dir.iterdir():
        if file_path.suffix != ".md":
            continue
        file_name = file_path.name
        file_name_id = parse_issue_id(file_name)
        try:
            content = file_path.read_bytes().decode("utf-8-sig")
            decode_error = False
        except UnicodeDecodeError:
            content = ""
            decode_error = True
        frontmatter = parse_issue_frontmatter(content)
        metadata = frontmatter.data
        issue_id = parse_frontmatter_id(metadata.get("id")) or file_name_id
        heading = get_issue_heading(frontmatter.body)
        heading_title = _clean_title(heading.group(1)) if heading else ""
        title = (
            _normalize(metadata.get("title"))
            or (heading_title if heading_title and not MOJIBAKE_PATTERN.search(heading_title) else "")
            or _title_from_file_name(file_name)
        )
        relative_path = file_path.relative_to(issues_path).as_posix()
        issues.append(
            Issue(
                id=issue_id,
                file_name_id=file_name_id,
                file_name=file_name,
                file_path=file_path,
                relative_path=relative_path,
                title=title,
                status=directory_status,
                issue_status=_normalize(metadata.get("status")) or directory_status,
                created=_normalize(metadata.get("created")),
                completed=_normalize(metadata.get("completed")),
                priority=_normalize(metadata.get("priority")),
                assignee=_normalize(metadata.get("assignee")),
                stage=_normalize(metadata.get("stage")),
                implementer=_normalize(metadata.get("implementer")),
                author=_normalize(metadata.get("author")),
                content=content,
                frontmatter=frontmatter,
                decode_error=decode_error,
            )
        )

    return sorted(issues, key=lambda issue: (issue.id or 0, issue.file_name))


def read_all_issues(issues_dir: Path | str) -> tuple[list[Issue], list[Issue], list[Issue]]:
    active_issues = read_issues(issues_dir, "active")
    completed_issues = read_issues(issues_dir, "completed")
    return active_issues, completed_issues, [*active_issues, *completed_issues]


def get_next_issue_id(issues: list[Issue]) -> int:
    return max((issue.id or 0 for issue in issues), default=0) + 1


def group_issues_by_id(issues: list[Issue]) -> dict[int, list[Issue]]:
    groups: dict[int, list[Issue]] = {}
    for issue in issues:
        if issue.id is None:
            continue
        groups.setdefault(issue.id, []).append(issue)
    return groups


def build_index_files(
    active_issues: list[Issue],
    completed_issues: list[Issue],
    recent_count: int = 30,
) -> dict[str, str]:
    files: dict[str, str] = {}
    files["active.md"] = _page(
        "Active Issues",
        _active_table(active_issues) if active_issues else "No active issues.",
    )

    recent_issues = sorted(completed_issues, key=lambda issue: issue.id or 0, reverse=True)[
        :recent_count
    ]
    files["completed-recent.md"] = _page(
        "Recently Completed Issues",
        _completed_table(recent_issues),
    )

    max_id = max((issue.id or 0 for issue in completed_issues), default=0)
    ranges = [(1, 99)]
    ranges.extend((start, start + 99) for start in range(100, max_id + 1, 100))

    for start, end in ranges:
        range_issues = [
            issue for issue in completed_issues if issue.id is not None and start <= issue.id <= end
        ]
        files[_range_name(start, end)] = _page(
            f"Completed Issues {start:03d}-{end:03d}",
            _completed_table(range_issues),
        )
    return files


def read_index_files(issues_dir: Path | str) -> list[str]:
    indexes_dir = Path(issues_dir) / "indexes"
    if not indexes_dir.exists():
        return []
    return sorted(path.name for path in indexes_dir.iterdir() if path.suffix == ".md")


def has_mojibake(text: str) -> bool:
    return bool(MOJIBAKE_PATTERN.search(text))


def has_non_ascii(text: str) -> bool:
    return bool(NON_ASCII_PATTERN.search(text))


def is_valid_workflow_token(value: str) -> bool:
    return value == "" or bool(WORKFLOW_TOKEN_PATTERN.fullmatch(value))


def _clean_title(title: str) -> str:
    return re.sub(r"\s+", " ", title).strip()


def _normalize(value: object) -> str:
    return "" if value is None else str(value).strip()


def slugify(
    value: str,
    *,
    default: str,
    max_len: int | None = None,
) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", value.lower())
    slug = re.sub(r"_+", "_", slug).strip("_")
    if max_len is not None:
        slug = slug[:max_len]
    return slug or default


def _title_from_file_name(file_name: str) -> str:
    return re.sub(r"\.md$", "", re.sub(r"^\d+_", "", file_name))


def _issue_link(issue: Issue) -> str:
    return f"[{issue.relative_path}](../{issue.relative_path})"


def _active_table(issues: list[Issue]) -> str:
    lines = [
        "| ID | Title | Priority | Status | File |",
        "| --- | --- | --- | --- | --- |",
    ]
    for issue in issues:
        lines.append(
            f"| {issue.id or ''} | {issue.title} | {issue.priority or '-'} | "
            f"{issue.issue_status or 'active'} | {_issue_link(issue)} |"
        )
    return "\n".join(lines)


def _completed_table(issues: list[Issue]) -> str:
    lines = [
        "| ID | Title | Completed | File |",
        "| --- | --- | --- | --- |",
    ]
    for issue in issues:
        lines.append(
            f"| {issue.id or ''} | {issue.title} | {issue.completed or '-'} | {_issue_link(issue)} |"
        )
    return "\n".join(lines)


def _page(title: str, body: str) -> str:
    return f"""# {title}

This file is generated by `issuekit generate-indexes`. Do not edit it by hand.

{body}
"""


def _range_name(start: int, end: int) -> str:
    return f"completed-{start:03d}-{end:03d}.md"
