"""Agent prompt templates and paired structured-output contracts."""

from .spec import (
    NEGOTIATION_RESUMED_ROUND_PROMPT,
    NEGOTIATION_ROUND_PROMPT,
    PROMPT_SPECS,
    PROPOSAL_CHECK_PROMPT,
    REVIEW_PROMPT,
    ROUTER_PROMPT,
    SHARED_PARTIALS,
    TEMPLATE_NAMES,
    TRIAGE_PROMPT,
    NegotiationParseError,
    PromptSpec,
    ProposalCheckParseError,
    ReviewParseError,
    RouterParseError,
    TriageAuthorParseError,
    load_template,
    parse_newest_json_block,
    render_negotiation_round_pointer,
    render_review_feedback_prompt,
    render_template,
)

__all__ = [
    "NEGOTIATION_RESUMED_ROUND_PROMPT",
    "NEGOTIATION_ROUND_PROMPT",
    "PROMPT_SPECS",
    "PROPOSAL_CHECK_PROMPT",
    "REVIEW_PROMPT",
    "ROUTER_PROMPT",
    "SHARED_PARTIALS",
    "TEMPLATE_NAMES",
    "TRIAGE_PROMPT",
    "NegotiationParseError",
    "PromptSpec",
    "ProposalCheckParseError",
    "ReviewParseError",
    "RouterParseError",
    "TriageAuthorParseError",
    "load_template",
    "parse_newest_json_block",
    "render_negotiation_round_pointer",
    "render_review_feedback_prompt",
    "render_template",
]
